
# Custom Script for VMs
script = """#!/bin/bash
sudo apt update
sudo apt install -y nginx
echo "Hi, I am the Azure Instance {instance_number} generated by Pulumi" | sudo tee /var/www/html/index.html
sudo systemctl start nginx
"""


from pulumi_azure_native import compute, network

def create_vm_in_az(region, az, resource_group, vnet, subnet):
    # Create NIC with availability zone
    nic = network.NetworkInterface(
        f"nic-{region}-{az}",
        resource_group_name=resource_group.name,
        location=region,
        ip_configurations=[network.NetworkInterfaceIPConfigurationArgs(
            name="ipconfig1",
            subnet=network.SubnetArgs(id=subnet.id),
            private_ip_allocation_method="Dynamic",
        )],
        availability_zone=az,  # Assign availability zone to NIC
    )
    
    # Create VM with NIC in specific AZ
    vm = compute.VirtualMachine(
        f"vm-{region}-{az}",
        resource_group_name=resource_group.name,
        location=region,
        hardware_profile=compute.HardwareProfileArgs(
            vm_size="Standard_B1s",
        ),
        storage_profile=compute.StorageProfileArgs(
            os_disk=compute.OSDiskArgs(
                create_option="FromImage",
                managed_disk=compute.ManagedDiskParametersArgs(storage_account_type="Standard_LRS"),
            ),
            image_reference=compute.ImageReferenceArgs(
                publisher="Canonical",
                offer="UbuntuServer",
                sku="20.04-LTS",
                version="latest",
            ),
        ),
        network_profile=compute.NetworkProfileArgs(
            network_interfaces=[compute.NetworkInterfaceReferenceArgs(
                id=nic.id,
            )],
        ),
    )
