import pulumi
import pulumi_azure as azure
import pulumi_azure_native as azure_native
from pulumi_azure_native import compute, network

# ------------------------------------------------------------------

def create_nic_in_az(region, resource_group, region_subnet_private, az):
    nic = azure_native.network.NetworkInterface(
        f"nic-{region}-AZ{az}-",
        resource_group_name=resource_group.name,
        location=region,
        #availability_zone=az,
        ip_configurations=[{
            "name": "ipconfig1",
            "subnet": {
                "id": region_subnet_private
            },
            "private_ip_address_allocation": "Dynamic",
        }],
    )
    return nic

def create_vm_in_az(region, resource_group, region_az_nic, az):

    script = f"""
#!/bin/bash
sudo apt update
sudo apt install -y nginx
echo "Hi, I am the Azure Instance in region {region}, AZ {az}, generated by Pulumi" | sudo tee /var/www/html/index.html
sudo systemctl start nginx
"""

    virtual_machine = azure.compute.VirtualMachine(
        f"vm-{region}-{az}",
        resource_group_name=resource_group.name,
        location=region,
        zones=az,
        network_interface_ids=[region_az_nic.id],
        vm_size="Standard_B1s",
        storage_image_reference={
            "publisher": "Canonical",
            "offer": "0001-com-ubuntu-server-jammy",
            "sku": "22_04-lts",
            "version": "latest",
        },
        storage_os_disk={
            "name": "myosdisk1",
            "caching": "ReadWrite",
            "create_option": "FromImage",
            "managed_disk_type": "Standard_LRS",
            "disk_size_gb": 30,
        },
        os_profile={
            "computer_name": "hostname",
            "admin_username": "testadmin",
            "admin_password": "Password1234!",
            "custom_data": script,
        },
        os_profile_linux_config={
            "disable_password_authentication": False,
        },
    )
    return virtual_machine

# ------------------------------------------------------------------
